// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.14.0-beta.2.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

CoreStatus initializeCore() =>
    RustLib.instance.api.crateApiCoreInitializeCore();

AboutInfo getAboutInfo() => RustLib.instance.api.crateApiCoreGetAboutInfo();

class AboutInfo {
  final String appName;
  final String appVersion;
  final String packageName;
  final String architecture;
  final String coreVersion;
  final String license;

  const AboutInfo({
    required this.appName,
    required this.appVersion,
    required this.packageName,
    required this.architecture,
    required this.coreVersion,
    required this.license,
  });

  @override
  int get hashCode =>
      appName.hashCode ^
      appVersion.hashCode ^
      packageName.hashCode ^
      architecture.hashCode ^
      coreVersion.hashCode ^
      license.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AboutInfo &&
          runtimeType == other.runtimeType &&
          appName == other.appName &&
          appVersion == other.appVersion &&
          packageName == other.packageName &&
          architecture == other.architecture &&
          coreVersion == other.coreVersion &&
          license == other.license;
}

class CoreStatus {
  final bool ready;
  final String coreVersion;
  final int dataSchemaVersion;
  final String? error;

  const CoreStatus({
    required this.ready,
    required this.coreVersion,
    required this.dataSchemaVersion,
    this.error,
  });

  @override
  int get hashCode =>
      ready.hashCode ^
      coreVersion.hashCode ^
      dataSchemaVersion.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreStatus &&
          runtimeType == other.runtimeType &&
          ready == other.ready &&
          coreVersion == other.coreVersion &&
          dataSchemaVersion == other.dataSchemaVersion &&
          error == other.error;
}
